<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "weather_widget"
 *
 * Auto generated by Extension Builder 2020-09-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Weather Widget',
    'description' => 'Weather by Wttr.in',
    'category' => 'plugin',
    'author' => 'Sven Jürgens',
    'author_email' => 'typo3@blue-side.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.2',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
