services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SvenJuergens\WeatherWidget\:
    resource: '../Classes/*'

  cache.dashboard.weather:
    class: 'TYPO3\CMS\Core\Cache\Frontend\FrontendInterface'
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments:
      $identifier: 'dashboard_weather'

  dashboard.widget.weatherWidget:
    class: 'SvenJuergens\WeatherWidget\Widgets\WeatherWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $cache: '@cache.dashboard.weather'
      $options:
        location: 'Berlin'
    tags:
      - name: dashboard.widget
        identifier: 'weatherWidget'
        groupNames: 'general'
        title: 'LLL:EXT:weather_widget/Resources/Private/Language/locallang.xlf:widgets.weather.title'
        description: 'LLL:EXT:weather_widget/Resources/Private/Language/locallang.xlf:widgets.weather.description'
        iconIdentifier: 'actions-cloud'
        height: 'medium'
        width: 'small'
